### PR TITLE
pdksync - add dependency marktlib

### PR DESCRIPTION
**Pull request by Lightning-**
add dependency marktlib
pdk version: `3.2.0`

### CODE REVIEW

**Comment by oxc** [comment]
This will get released as a major version change, right?

**Comment by Lightning-** [comment]
not necessarily as a major: currently we're just adding this as a dependency to all of our modules but without being used (yet).

starting a great makeover of all modules we own, those reworks might trigger a minor or major release, depending on the changes. but most likely there will drop out some majors as our changes will likely be big and incisive ;).

but the dependency to marktlib should be some sort of no-brainer (for now) because marktlib itself just provides features without actively replacing other existing mechanics or interfering with other modules.

**Comment by oxc** [comment]
If this ever gets used, people need to actively add this to their Puppetfile, which IMHO warrants a major version bump according to semver, because nobody reads CHANGELOGs on every minor bump.

Relying on the first person to use the new types/features to think of this is IMHO a recipe for failure :) (Or alternatively: if it's not used yet, what good is having the dependency in the first place. Just add it when you need it.)

**Comment by Lightning-** [comment]
> because nobody reads CHANGELOGs on every minor bump

ok, thinking this way ... indeed, we need a major :laughing:

but as said, we won't release just to introduce a new dependency that's not used yet. the changes being worked on are the more interesting part, and work just started.

so stay tuned :smile:

**Pull request merged**
